---
title: About me
date: '2017-03-08'
draft: no
---

### In one sentence

I'm an interdisciplinary ecologist in the private sector with a focus on aquatic assessments, microbiology, study design, statistical analysis, and data visualization.


### Frydenborg Ecologic, LLC

I have a background in wetlab bench research. During my undergraduate studies, I was privileged to receive several awards and fellowships that allowed me to conduct research in laboratories while earning my degree. I worked on understanding cellular regulation and developmental biology in both plants and animals. Later I switched focus to the fascinating microscopic world, applying similar molecular methods to understanding the ecology of microbes, and their relationship to human and ecosystem health. Although I enjoyed being a part of basic research, I decided to leave academia due to the uncertain job market, as well as feeling rather burned out by the grind and hours that banging your head against the frontier of knowledge entails.

I've long been a proponent of science-based policies and evidence-based decision making, and saw an opportunity to engage in this process in a meaningful way by starting a consulting company, Frydenborg Ecologic. I started the company along with my dad in 2014, and I now find myself working at the intersection of policy and science. Our company has worked with private and public stakeholders on projects concerning Numeric Nutrient Criteria, Environmental Resource Permitting, Waste Water Treatment Facility permits, NPDES compliance, Microbial Source Tracking, policy reviews and meta-analyses, and ecological restoration. I find the work consistently interesting, challenging, and rewarding. I get to work on complex problems that have time and resource restraints, clear consequence and impact, and controversy driven by non-scientific ideology. There are very few boring days.


You can visit the [company website here](http://www.frecologic.com/).

#### Education

M.S., Environmental Health Science
University of Georgia, 2013
 
Thesis: Preliminary analysis of the viral influence on the holobiont of Elkhorn coral, *Acropora palmata*, in the context of temperature associated white pox disease
 
B.S., Microbiology and Cell Science
University of Florida, 2010     

#### Relavent Skills
*Computer:* R/Rstudio, Shiny application development, QGIS, GRASS, SAGA, GitHub/git
*Field:* PADI Scientific Diving (50 dives), FDEP Stream Condition Index, FDEP Habitat Assessment

#### 